# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.275
    hooks:
    -   id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.0
    hooks:
    -   id: mypy
        args: [--strict]
        additional_dependencies: [typer==0.9.0, asyncpg-stubs==0.28.0, pydantic==2.2.1, pydantic_settings==2.0.3, python-dotenv==1.0.0, httpx==0.24.1]
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.11
