SHELL := /bin/bash
PYTHON_SOURCES = gh_automation_funda/ stubs/

install:
	poetry install

format-check:
	poetry run isort --check $(PYTHON_SOURCES)
	poetry run black --check $(PYTHON_SOURCES)
	poetry run ruff check $(PYTHON_SOURCES)
	poetry run mypy $(PYTHON_SOURCES)

format:
	poetry run isort $(PYTHON_SOURCES)
	poetry run black $(PYTHON_SOURCES)
	poetry run ruff check $(PYTHON_SOURCES) --fix
	poetry run mypy $(PYTHON_SOURCES)
